config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/logout', to: 'sessions#logout'
  end

  devise_for :users, controllers: {
          sessions: 'users/sessions'
        }

  get 'bike_parts/:id', to: 'bike_parts#show', as: :show_bike_part

  resources :orders
  post 'payment_received/:id', to: 'orders#payment_received', as: :payment_received

	get '/auth/:provider/callback', to: 'sessions#create'

	post '/toggle_admin', to: 'users#toggle_admin'



  resources :products
  resources :parts
  get 'users/search' => 'users#search'
  get 'users/search/:q' => 'users#search'

  get '/parts/search:q' => 'parts#search'


  get 'delivered_to_service/:id' => 'services#delivered_to_service', as: :delivered_to_service
  get 'receipt_for_new_service/:id' => 'services#receipt_for_new_service',
    as: :receipt_for_new_service

  resources :bikes do
    resources :services
  end

  get '/services/new_with_parts_selected/:bike_id' \
        => 'services#new_with_parts_selected', as: :get_new_service_with_parts_selected
  post '/services/new_with_parts_selected/:bike_id' \
        => 'services#new_with_parts_selected', as: :new_service_with_parts_selected

  resources :services do
  end

  resources :users do
    get 'fetch_bikes_from_strava' => 'users#fetch_bikes_from_strava'
    resources :bikes do
      get '/parts'  => 'bikes#parts'
      post '/:id'   => 'bikes#add_part'
      delete '/:id' => 'bikes#remove_part'
    end
  end


  get '/order' => 'front_page#order'
  get '/service_booklet' => 'front_page#service_booklet'
  post '/contact_form' => 'front_page#contact_form'

  root 'front_page#index'

end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id                   :integer          not null, primary key
#  description          :string
#  log                  :string
#  due_date             :date
#  bike_id              :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  completed            :boolean          default(FALSE)
#  delivered_to_service :boolean          default(FALSE)
#

class Service < ActiveRecord::Base
  belongs_to :bike
  has_many :part_services, dependent: :destroy

  scope :in_progress, -> { where(completed: false) }
  scope :delivered_to_service, -> { where(delivered_to_service: true) }
  scope :not_completed, -> { where(completed: false) }
  scope :completed, -> { where(completed: true) }

  def state_class
    if completed
      return "alert alert-success completed"
    elsif delivered_to_service
      return "alert alert-info delivered_to_service"
    else
      return "alert alert-warning awaiting_delivery"
    end
  end

  def state
    if completed
      return "Ferdig"
    elsif delivered_to_service
      return "Levert til service"
    else
      return "Venter på at sykkelen blir levert inn"
    end
  end

  def delivered_to_service!
    self.update(delivered_to_service: true)
    self.update(completed: false)
    self.save!
  end

  def bike_parts
    part_services.collect{ |service| service.bike_part }
  end

  def complete!(bike_part_ids, service_logs)
    self.update(completed: true)
    distance = BikePart.find(bike_part_ids.first).bike.distance
    BikePart.find(bike_part_ids).each_with_index do |bp,i|
      bp.update(service_done_at_bike_distance: distance)
      bike_part_service = bp.part_services.last
      bike_part_service.update!(completed: true,
                                log: service_logs[i])
    end
  end

  def complete?
    part_services.detect{ |ps| ps.completed == false }.blank?
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update,
                                     :destroy, :receipt_for_new_service, :delivered_to_service]
  before_action :set_bike_part, only: [:new, :create, :new_with_parts_selected]
  before_action :set_bike_part_from_service, only: [:edit, :update]
  before_action :set_bike, only: [:new_with_parts_selected, :update]



  # This page shows the receipt the customer tapes to his bike before delivering it
  def registered
    set_service
  end

  def register_bike_in
    set_service
    @service.update(:delivered_to_service, true)
  end


  # GET /services
  # GET /services.json
  def index
    @services = Service.all.delivered_to_service.not_completed.order(:created_at)
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end


  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
    @bike = @service.bike
  end

  def find_user
  end

  # This page displays information regarding the service the user has ordered.
  # The user should print this and bring it with his bike.
  def receipt_for_new_service

  end

  def new_with_parts_selected
    @parts = BikePart.find(params[:bike_part_id])
    @service = @bike.services.new
  end

  # POST /services
  # POST /services.json
  #
  # Creating a new service requires a bike and the parts that are involved.
  #
  def create
    @service = []
    description = params["service_description"]

    # Create the Bike Service first
    @service = @bike.services.create

    # Then one service for each part
    bike_parts = []
    bike_parts << BikePart.find(params[:bike_part_id])
    bike_parts.flatten!

    bike_parts.each_with_index do |bike_part, i|
      distance = @bike.distance
      @service.part_services.create!(description: description[i],
                                     bike_part: bike_part,
                                     service_completed_at_milage: distance)
    end

    respond_to do |format|
      if @service.save
        $mixpanel.track('Admin', 'Registered a service')
        format.html { redirect_to [@bike.user, @bike],
                      notice: 'Service på sykkelen er registrert. '+
                              'Nå er det bare å levere inn sykkelen til Marcos sykkelverksted'
                    }
        format.json { render :show, status: :created, location: @service }
      else
        Rails.logger.debug "SERVICES ==NOT== SAVED"
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update!(service_params)
        completed = params[:service][:completed] ? true : false

        if completed
          $mixpanel.track('Admin', 'Service completed') if completed
          @service.complete!(params[:bike_part_id], params[:log])
        end

        notice = @service.completed? ? 'Service marked as complete' : 'Updated'
        format.html { redirect_to services_path, notice: notice }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to user_bike_url(@service.bike.user, @service.bike),
                    notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delivered_to_service
    @service.delivered_to_service!
    redirect_to @service.bike.user, notice: "Innlevert"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    def set_bike
      @bike = Bike.find(params[:bike_id])
    end

    def set_bike_part_from_service
      @bike_parts = @service.bike_parts
    end

    def set_bike_part
      @bike_parts = []
      @bike_parts << BikePart.find(params[:bike_part_id])
      @bike_parts.flatten!
      @bike = @bike_parts.first.bike
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:description, :log, :due_date, :bike_id,
                    :user_id, :completed, bike_part_id: [])
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.slim
= render partial: 'layouts/form_error_messages',
  locals: { form_object: @service }

.form-horizontal
  = form_for [@bike, @service] do |f|

    - @bike_parts.each do |p|
      h3= p.kind
      = text_field_tag("bike_part_id[]", p.id, class: 'hidden')
      br
      .form-group
        label(for="service_description[]") Beskrivelse
        = text_area_tag("service_description[]",
          (p.service_description || 'Placeholder: Oil and replace worn parts'),
           rows: 5, class: 'form-control')
      - unless @service.new_record?
        .form-group
          label(for="log[]") Log
          = text_area_tag("log[]",
            (p.service_description || 'Placeholder: What has been done'),
            rows: 5, class: 'form-control')
      br
      hr
      /= f.fields_for :bike_part_service do |bike_part_service|
        em bike_part_service
        = bike_part_service.description :description

    /.form-group
      = f.label :description
      = f.text_area :description, class: 'form-control', rows: 6,
        placeholder: "- What does the customer want us to help with? \n" \
        "- Have we agreed upon a price? \n" \
        "- Anything we should check up and call the customer about?"


    /.form-group
      = f.label :due_date
      br
      = f.datetime_select :due_date, start_year: Time.now.year,
        end_year: Time.now.year+1, order: [:day, :month, :year]

    - unless @service.new_record?
      .form-group
        .checkbox
          label
            = check_box_tag 'service[completed]', true, @service.completed
            | Ferdig



    .form-group
        = f.submit :class => 'btn btn-primary', value: 'Lagre'
        = link_to 'Tilbake', :back, class: 'btn'

app/views/services/_service.html.slim
.box-shadow
  .pull-right.text-right
    span Service nr:
    h4.label.label-info = service.id
    - if service.present?
      p(class= "service_status #{service.state_class}") = service.state

    br

  - unless body_id == 'bikes_show'
    h2= link_to service.bike.name, [service.bike.user, service.bike]
    p.text-muted.clearfix
      = link_to service.bike.user.name, service.bike.user

    - if service.bike.image?
      .row
        .col-sm-6.col-md-4
          .img-responsive.thumbnail
            = image_tag(service.bike.image_url, width: '400')

  - service.part_services.each do |part_service|
    .well
      h3= part_service.bike_part.kind
      hr

      strong Beskrivelse av service
      br
      = simple_format part_service.description

      - if part_service.log.present?
        br
        br
        p
          strong Log
          = simple_format part_service.log
      br

  br
  br
  br
  .button-group
    - if service.persisted? && admin?
      = link_to 'Rediger', edit_bike_service_path(service.bike, service),
        class: 'btn btn-primary'
      = link_to 'Merk som innlevert', delivered_to_service_path(service),
        class: 'btn btn-success' unless service.delivered_to_service
    - if (( service.bike.user == current_user ) || service.state.blank?) || admin?
      = link_to 'Slett', bike_service_path(service.bike, service),
        data: { confirm: "Sikker?" }, method: :delete,
        class: 'btn btn-warning pull-right'

app/views/services/edit.html.slim
- content_for :breadcrumb do
  li= link_to 'Customers', users_path
  li= link_to @service.bike.user.name, @service.bike.user
  li= link_to @service.bike.name, [@service.bike.user, @bike]
  li
    strong= Service

h1= "Service for #{@bike.name}"


.container
  == render 'form'

app/views/services/index.html.slim
- if @services.empty?
  span Bra jobba! Alle syklene er reparert! :-)
- else
  h1 Sykler som må fikses

  = render @services

br

br
br
br
= link_to 'Registrer ny service', users_search_path, class: 'btn btn-success'

app/views/services/new.html.slim
- content_for :breadcrumb do
  li= link_to 'Customers', users_path
  li= link_to @bike.user.name, @bike.user
  li= link_to @bike.name, @bike
  li
    strong Register new service


== render 'form'

app/views/services/new_with_parts_selected.html.slim
- content_for :breadcrumb do
  li= link_to 'Customers', users_path
  li= link_to @bike.user.name, @bike.user
  li= link_to @bike.name, @bike
  li
    strong Register new service


== render 'form'

= link_to 'Back', bike_services_path

app/views/services/receipt_for_new_service.html.slim
- content_for :breadcrumb do
  - if admin?
    li= link_to 'Kunder', users_path
  li= link_to current_user.name, current_user
  li
    strong Følgelapp

h3 Følgelapp for service


= render @service

app/views/services/register_bike_in.html.slim
h1 Søk etter service

app/views/services/registered.html.slim
.alert.alert-info
  strong Print ut denne lappen og fest den på sykkelen din før du leverer den til oss på Birksport Alnabru.

= render @service

app/views/services/show.html.slim
- content_for :breadcrumb do
  li= link_to 'Customers', users_path
  li= link_to @bike.user.name, @bike.user
  li= link_to @bike.name, [@bike.user, @bike]
  li
    strong= Service

= render @service