config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/logout', to: 'sessions#logout'
  end

  devise_for :users, controllers: {
          sessions: 'users/sessions'
        }

  get 'bike_parts/:id', to: 'bike_parts#show', as: :show_bike_part

  resources :orders
  post 'payment_received/:id', to: 'orders#payment_received', as: :payment_received

	get '/auth/:provider/callback', to: 'sessions#create'

	post '/toggle_admin', to: 'users#toggle_admin'



  resources :products
  resources :parts
  get 'users/search' => 'users#search'
  get 'users/search/:q' => 'users#search'

  get '/parts/search:q' => 'parts#search'


  get 'delivered_to_service/:id' => 'services#delivered_to_service', as: :delivered_to_service
  get 'receipt_for_new_service/:id' => 'services#receipt_for_new_service',
    as: :receipt_for_new_service

  resources :bikes do
    resources :services
  end

  get '/services/new_with_parts_selected/:bike_id' \
        => 'services#new_with_parts_selected', as: :get_new_service_with_parts_selected
  post '/services/new_with_parts_selected/:bike_id' \
        => 'services#new_with_parts_selected', as: :new_service_with_parts_selected

  resources :services do
  end

  resources :users do
    get 'fetch_bikes_from_strava' => 'users#fetch_bikes_from_strava'
    resources :bikes do
      get '/parts'  => 'bikes#parts'
      post '/:id'   => 'bikes#add_part'
      delete '/:id' => 'bikes#remove_part'
    end
  end


  get '/order' => 'front_page#order'
  get '/service_booklet' => 'front_page#service_booklet'
  post '/contact_form' => 'front_page#contact_form'

  root 'front_page#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first_name             :string
#  last_name              :string
#  email                  :string
#  mobile                 :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  provider               :string
#  uid                    :string
#  username               :string
#  role                   :string           default("normal")
#  strava_omniauth_code   :string
#  access_token           :string
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#

# The User class is used for authenication for the system.
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bikes, dependent: :destroy
  has_many :services, through: :bikes
  validates :first_name, :last_name, presence: true
  validates :mobile, :email, uniqueness: true, allow_blank: true

  scope :services_in_progress, -> { where(field: value) }

  def name
    "#{first_name} #{last_name}"
  end

  def fetch_bikes_from_strava
    user_data = fetch_athlete_from_strava
    return if user_data["bikes"].blank?

    user_data["bikes"].each do |b|
      distance_in_km = b["distance"] / 1000
      puts "Saving distance #{distance_in_km} for b.name"
      bike = self.bikes.find_or_create_by(strava_id: b['id'])
      bike.update_attributes(name: b["name"], distance: distance_in_km)
    end
  end


  def fetch_athlete_from_strava
    HTTParty.get( "https://www.strava.com/api/v3/athlete",
                   headers: {"Authorization" => "Bearer #{access_token}"} )
  end

  def self.fetch_user_data(code)
    client_id     = ENV["STRAVA_CLIENT_ID"]
    client_secret = ENV["STRAVA_CLIENT_SECRET"]
    HTTParty.post( "https://www.strava.com/oauth/token?" +
                   "client_id=#{client_id}" +
                   "&client_secret=#{client_secret}" +
                   "&code=#{code}")
  end


  def self.from_strava_omniauth(code)
    user_data = fetch_user_data(code)
    if fetch_user_data(code).response.code.match("400")
      raise "Fetching user failed: #{user_data.response.body}"
    end
    username  = user_data.parsed_response["athlete"]["username"]
    user = where( { username: username, provider: :strava })
      .first || create_from_omniauth(user_data)

    user.update_attribute(:strava_omniauth_code,  code)
    user
  end

  def self.create_from_omniauth(user_data)
		user_object              = OpenStruct.new(user_data["athlete"])
    user_object.access_token = user_data["access_token"]
    create! do |user|
      user.access_token = user_object.access_token
      user.email        = user_object.email
      user.first_name   = user_object.firstname
      user.last_name    = user_object.lastname
      user.provider     = :strava
      user.username     = user_object.username
    end
  end

  def admin?
    role.to_sym == :admin
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update ]
  before_action :only_admins, except: [:show, :fetch_bikes_from_strava, :edit, :update]
  #before_action :authenticate_user!


  #http_basic_authenticate_with name: "bike", password: "lover"

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def toggle_admin
    return unless admin?
    session[:admin_menu] = !session[:admin_menu]
    redirect_to :back
  end


  def search
    first,last = params[:q].split if params[:q].present?
    if params[:q]
       @users = User.where('first_name ILIKE ? AND last_name ILIKE ?',
                                "%#{first}%", "%#{last}%")
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @services_in_progress = @user.services.in_progress
    @service_history      = @user.services.completed
    @bikes                = @user.bikes
  end


  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Bruker lagret' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Oppdatert brukerkonto lagret' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fetch_bikes_from_strava
    current_user.fetch_bikes_from_strava
    redirect_to current_user, notice: "Bikes imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def only_admins
      redirect_to root_url, :flash => { notice: 'Only for admins' } \
        unless current_user && current_user.admin? || current_user == @user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :mobile)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= form_for @user do |f|
  = render partial: 'layouts/form_error_messages',
    locals: { form_object: @user }


  .form-group
    = f.label :first_name, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :first_name, class: 'form-control'
  .form-group
    = f.label :last_name, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :last_name, class: 'form-control'
  .form-group
    = f.label :mobile, class: 'control-label col-sm-2'
    .col-sm-10
      = f.number_field :mobile, class: 'form-control'
  .form-group
    = f.label :email, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_area :email, class: 'form-control'

  = f.submit :class => 'btn btn-primary'

app/views/users/_header.html.slim
.pull-right
  = link_to 'Rediger', edit_user_path(@user)
h3= @user.name
span= "Mobil: #{@user.mobile}"
br
- if @user.email.present?
  span= "E-post: #{@user.email}"


br
br

app/views/users/edit.html.slim
- content_for :breadcrumb do
  - if admin?
    li= link_to 'Kunder', users_path
  li= link_to @user.name, @user
  li
    strong Rediger

h1 Rediger profil

== render 'form'

app/views/users/index.html.slim
br
h1 Kunde

table.table
  thead
    tr
      th Navn
      th Mobil
      th Epost
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = link_to user.name, user
        td = user.mobile
        td = user.email
        td = link_to 'Rediger', edit_user_path(user), class: 'btn'
        td
          = link_to 'Slett', user, data: {:confirm => 'Are you sure?'},
            :method => :delete, class: 'btn'

br

.btn-group
  = link_to 'Ny kunde', new_user_path, :class => 'btn btn-default'
  = link_to 'Søk', users_search_path, :class => 'btn btn-default'

app/views/users/new.html.slim
h1 Registrer ny kunde

== render 'form'

app/views/users/search.html.slim
h1 Søk etter kunde


= form_tag(users_search_path, method: 'get', id: 'q') do
  .input-group
    = text_field_tag 'q', nil, placeholder: 'Søk på navn..',
      class: 'form-control', value: params[:q]

    span.input-group-btn
      = submit_tag 'Søk', :class => 'btn btn-default'

- if @users.present?
  ul.users.list-group
    strong Treff:
    - @users.all.each do |c|
      li.list-group-item
        = link_to c.name, c
- elsif params[:q]
  .alert.alert-info(role="alert")
    = "Could not find #{params[:q]}"

hr
= link_to "Lag ny kunde", new_user_path, :class => 'btn btn-primary'
= link_to "Vis alle kunder", users_path, :class => 'btn'

app/views/users/show.html.slim
- content_for :breadcrumb do
  - if admin? && session[:admin_menu]
    li= link_to 'Kunder', users_path
  li
    strong= @user.name

= render 'header'

ul.nav.nav-tabs role='tablist'
  - if @services_in_progress.present?
    li(role="presentation"
      class="#{ (@services_in_progress.present? ? 'active' : '') }")
      a href="#this_service"  data-toggle="tab" Til reperasjon
  - if @service_history.present?
    li role="presentation"
      a href="#service_history"  data-toggle="tab" Historikk
  li(role="presentation"
    class="#{ (@services_in_progress.blank? ? 'active' : '') }")
    a href="#bikes" data-toggle="tab" Sykler

.tab-content
  - if @services_in_progress.present?
    #this_service.tab-pane.fade.in(class="#{ (@services_in_progress.present? ? 'active' : '') }")
      h2 Sykler til reparasjon
      = render @services_in_progress

  - if @service_history.present?
    #service_history.tab-pane.fade.in
      br
      br
      br
      - @service_history.each do |s|
        = render s

  - if @bikes.present?
    #bikes.tab-pane.fade.in(class="#{ (@services_in_progress.blank? ? 'active' : '') }")
      h3 Sykler
      .box-shadow
        ul.bikes
          - @bikes.each do |b|
            li = link_to b.name, [@user, b]
  br
  = link_to 'Legg til sykkel', new_user_bike_path(@user), class: 'btn btn-primary'
  - unless admin?
    - if @user.provider == 'strava'
      = link_to 'Hent sykler fra Strava',
        user_fetch_bikes_from_strava_path(@user), class: 'btn btn-primary'