config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/logout', to: 'sessions#logout'
  end

  devise_for :users, controllers: {
          sessions: 'users/sessions'
        }

  get 'bike_parts/:id', to: 'bike_parts#show', as: :show_bike_part

  resources :orders
  post 'payment_received/:id', to: 'orders#payment_received', as: :payment_received

	get '/auth/:provider/callback', to: 'sessions#create'

	post '/toggle_admin', to: 'users#toggle_admin'



  resources :products
  resources :parts
  get 'users/search' => 'users#search'
  get 'users/search/:q' => 'users#search'

  get '/parts/search:q' => 'parts#search'


  get 'delivered_to_service/:id' => 'services#delivered_to_service', as: :delivered_to_service
  get 'receipt_for_new_service/:id' => 'services#receipt_for_new_service',
    as: :receipt_for_new_service

  resources :bikes do
    resources :services
  end

  get '/services/new_with_parts_selected/:bike_id' \
        => 'services#new_with_parts_selected', as: :get_new_service_with_parts_selected
  post '/services/new_with_parts_selected/:bike_id' \
        => 'services#new_with_parts_selected', as: :new_service_with_parts_selected

  resources :services do
  end

  resources :users do
    get 'fetch_bikes_from_strava' => 'users#fetch_bikes_from_strava'
    resources :bikes do
      get '/parts'  => 'bikes#parts'
      post '/:id'   => 'bikes#add_part'
      delete '/:id' => 'bikes#remove_part'
    end
  end


  get '/order' => 'front_page#order'
  get '/service_booklet' => 'front_page#service_booklet'
  post '/contact_form' => 'front_page#contact_form'

  root 'front_page#index'

end

app/models/bike.rb
# == Schema Information
#
# Table name: bikes
#
#  id         :integer          not null, primary key
#  year       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  image      :string
#  user_id    :integer
#  name       :string
#  strava_id  :string
#  distance   :integer          default(0)
#

class Bike < ActiveRecord::Base

  has_many :bike_parts, dependent: :destroy
  has_many :parts, through: :bike_parts

  has_many :services, dependent: :destroy
  validates :name, :user, presence: true
  belongs_to :user

  after_create :add_default_parts

  mount_uploader :image, ImageUploader

  scope :services_in_progress,   -> { services.where(completed: false)  }

  def in_for_service?
    services.where(completed: false).present?
  end

  def parts_due_for_service
    bike_parts.map { |bp| bp if bp.service_due? }
  end

  def add_default_parts
    default_parts.each do |part|
      next unless part
      self.parts << part
    end
    save!
  end

  def default_parts
    Rails.logger.debug  "Found #{Part.where(model: 'generic').all}.size parts"
    Part.where(model: :generic).all
  end

  def self.due_for_service
    Bike.all.collect { |b| b if (b.parts_due_for_service.present?) }
  end

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]
  before_action :set_bike_from_id, only: [:parts, :add_part, :remove_part]
  before_action :set_user #, only: [:new, :create, :show]
  before_action :authenticate_user!

  before_action :only_admins, except: [:new, :create, :show, :edit, :update]

  def only_admins
    return if admin?
    return if @bike.user == current_user
    redirect_to root_url, alert: 'Only for admins'
  end

  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
    @service              = @bike.services.new
    service_registered_but_not_delivered
    #@services_in_progress = @bike.services.in_progress
    #@service_history      = @bike.services.completed
  end

  def parts
    @used_parts      = @bike.parts
    @available_parts = Part.all - @bike.parts
  end

  def add_part
    @part = Part.find params[:id]
    @bike.parts << @part
    @bike.save!
    head 200, content_type: "text/html"
  end

  def remove_part
    @bike.parts.delete Part.find(params[:id])
    @bike.save!
    head 200, content_type: "text/html"
  end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = @user.bikes.new(bike_params)

    respond_to do |format|
      if @bike.save
        $mixpanel.track('Admin', 'Created a bike')
        format.html { redirect_to @bike.user,
                      notice: 'Sykkel lagret!' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to [@user, @bike],
                      notice: 'Sykkel oppdatert!' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to [@bike.user], notice: 'Sykkelen ble slettet' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    def set_bike_from_id
      @bike = Bike.find(params[:bike_id])
    end

    def set_user
      @user = current_user # User.find(params[:user_id])
    end


    # Never trust parameters from the scary internet, only allow the white
    # list through.
    def bike_params
      params.require(:bike).permit(:brand, :model, :year, :image, :name, :distance)
    end

    def service_registered_but_not_delivered
      return unless @service.delivered_to_service
      @service = current_user.services.in_progress.first
      msg = "Hei," \
            "<br/>" \
            "Print ut kvitteringen du finner på  "\
            "#{view_context.link_to('denne siden ',
              receipt_for_new_service_path(@bike) )}" \
            "og ta den med deg til verkstedet. "
      flash[:notice] = msg
    end
end

app/helpers/bikes_helper.rb
module BikesHelper

  include ActionView::Helpers::NumberHelper


  def km_until_next_service(bike_part)
    km_until_next = bike_part.km_until_next_service

    if bike_part.in_for_service?
      return ["Til service nå", :service_now]
    end

    if km_until_next == 0
      return ["Nå", :now]
    elsif (km_until_next < 0)
      return ["#{ ActiveSupport::NumberHelper.number_to_human((km_until_next * -1 ), precision: 0)
               } km siden", :over]
    elsif (km_until_next > 0)
      return ["Om #{km_until_next.to_i} kilometer", :soon]
    end

  end
end

app/views/bikes/_bike.html.slim
.wellX
  .pull-right
    = link_to 'Rediger', edit_user_bike_path(@bike.user,@bike), class: 'btn btn-primary btm-xs'
    = link_to 'Slett', user_bike_path(@bike.user, @bike), method: :delete,
      data: { confirm: "Virkelig slette?" }, class: 'btn btn-warning'

  h2= bike.name
  br
  em= "Kilometerstand: #{@bike.distance}"
  br
  br
  - if bike.image?
    .row
      .col-sm-6.col-md-4
          = image_tag(bike.image_url, width: '400', class: 'img-responsive thumbnail')



  - if @bike.bike_parts.empty?
    em Det er ikke lagt inn noen sykkeldeler enda.
  - else
    .box-shadow
      = form_for [@bike, @service], url: new_bike_service_path(@bike, @service),
        method: :get do |f|
          table
            tr
              th Del
              //th Merke
              th Service intervall
              th Antall km til neste service
            - @bike.bike_parts.each do |bike_part|
              - text, klass = km_until_next_service(bike_part)
              tr
                td = link_to bike_part.kind, show_bike_part_path(bike_part)
                td(align="right") = "#{bike_part.service_interval.to_s} km "
                td(align="right" class=klass) = text
                - unless bike_part.in_for_service?
                  td = check_box_tag 'bike_part_id[]', bike_part.id, false

          br
          br
          = submit_tag 'Bestill service på valgte deler', class: 'btn btn-primary btm-xs'

app/views/bikes/_form.html.slim
= form_for [@user, @bike] do |f|
  = render partial: 'layouts/form_error_messages',
    locals: { form_object: @bike }

  .form-group
    = f.label :name, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :year, class: 'control-label col-sm-2'
    .col-sm-10
      = f.number_field :year, class: 'form-control'

  .form-group
    = f.label :distance, class: 'control-label col-sm-2'
    .col-sm-10
      = f.number_field :distance, class: 'form-control'

  .form-group
    = f.label :image, class: 'control-label col-sm-2'
    .col-sm-10
       = f.file_field :image

  br
  br

  = f.submit :class => 'btn btn-primary'

app/views/bikes/edit.html.slim
- content_for :breadcrumb do
  li= link_to 'Kunder', users_path
  li= link_to @bike.user.name, @bike
  li= link_to @bike.name, [@bike.user, @bike]
  li
    strong Rediger


h1 Rediger sykkel

== render 'form'

app/views/bikes/index.html.slim
h1 Listing all bikes

table
  thead
    tr
      th Brand
      th Model
      th Year
      th
      th
      th

  tbody
    - @bikes.each do |bike|
      tr
        td = bike.brand
        td = bike.model
        td = bike.year
        td = link_to 'Show', bike
        td = link_to 'Edit', edit_bike_path(bike)
        td = link_to 'Destroy', bike, data: {:confirm => 'Are you sure?'}, :method => :delete

br

app/views/bikes/new.html.slim
- content_for :breadcrumb do
  li= link_to 'Kunder', users_path
  li= link_to @user.name, @user
  li
    strong Legg til sykkel

== render 'form'

app/views/bikes/parts.html.slim
- content_for :breadcrumb do
  li= link_to 'Kunder', users_path
  li= link_to @bike.user.name, @bike.user
  li= link_to @bike.name, [@bike.user, @bike]
  li
    strong= "Deler"

h3 Legg til deler

= react_component('BikePartList',
    availableParts: @available_parts,
    usedParts: @used_parts,
    bike: @bike,
    hide_menu: true )


br
= link_to 'Tilbake til sykkel', [@bike.user, @bike], class: 'btn btn-primary'

app/views/bikes/show.html.slim
- content_for :breadcrumb do
  li= link_to 'Kunder', users_path
  li= link_to @bike.user.name, @bike.user
  li= link_to 'Sykler', @bike.user
  li
    strong= @bike.name


ul.nav.nav-tabs
  - if @service_history.present?
    li role="presentation"
      a href="#service_history"  data-toggle="tab" Service historikk



.tab-content
  #bike.tab-pane.fade.in.active
    = render @bike
    br

  - if @services_in_progress.present?
    #this_service.tab-pane.fade.in
      h2 Inne for service
      = render @services_in_progress

  - if @service_history.present?
    #service_history.tab-pane.fade
      - @service_history.each do |s|
        = render s

br
br
br

= link_to 'Legg til eller fjern deler', user_bike_parts_path(@bike.user, @bike), class: 'btn btn-primary'