config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/logout', to: 'sessions#logout'
  end

  devise_for :users, controllers: {
          sessions: 'users/sessions'
        }

  get 'bike_parts/:id', to: 'bike_parts#show', as: :show_bike_part

  resources :orders
  post 'payment_received/:id', to: 'orders#payment_received', as: :payment_received

	get '/auth/:provider/callback', to: 'sessions#create'

	post '/toggle_admin', to: 'users#toggle_admin'



  resources :products
  resources :parts
  get 'users/search' => 'users#search'
  get 'users/search/:q' => 'users#search'

  get '/parts/search:q' => 'parts#search'


  get 'delivered_to_service/:id' => 'services#delivered_to_service', as: :delivered_to_service
  get 'receipt_for_new_service/:id' => 'services#receipt_for_new_service',
    as: :receipt_for_new_service

  resources :bikes do
    resources :services
  end

  get '/services/new_with_parts_selected/:bike_id' \
        => 'services#new_with_parts_selected', as: :get_new_service_with_parts_selected
  post '/services/new_with_parts_selected/:bike_id' \
        => 'services#new_with_parts_selected', as: :new_service_with_parts_selected

  resources :services do
  end

  resources :users do
    get 'fetch_bikes_from_strava' => 'users#fetch_bikes_from_strava'
    resources :bikes do
      get '/parts'  => 'bikes#parts'
      post '/:id'   => 'bikes#add_part'
      delete '/:id' => 'bikes#remove_part'
    end
  end


  get '/order' => 'front_page#order'
  get '/service_booklet' => 'front_page#service_booklet'
  post '/contact_form' => 'front_page#contact_form'

  root 'front_page#index'

end

app/views/layouts/_footer.html.slim
footer
  .row
    .col-sm-4
      h4
        | Kontakt oss
      address
        strong
          | Birksport Alnabru
        br
        |  Smalvollveien 63, 0667 Oslo
        br
      address
        abbr[title="Phone"]
          | P:
        |  464 49 152
        br
        abbr[title="Email"]
          | E:
        a[href="mailto:alnabru@birk.no"]
          | Alnabru@birk.no

//script[src="/bootstrap/js/jquery.js"]
//script[src="/bootstrap/js/bootstrap.min.js"]

app/views/layouts/_form_error_messages.html.slim
- if form_object.errors.any?
  #error_explanation
    h2 = "#{form_object.errors.count} feil hindret oss i å lagre:"
    ul
      - form_object.errors.full_messages.each do |message|
        li = message

app/views/layouts/_head.html.slim
head

  meta charset="utf-8" /
  meta content="IE=edge" http-equiv="X-UA-Compatible" /
  meta content="width=device-width, initial-scale=1" name="viewport" /
  /! The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags
  meta content="" name="description" /
  meta content="" name="author" /
  title Marcos Sykkelverksted


  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-inverse
  ul.nav.navbar-nav
    - if admin_menu?
      li(class="#{ body_id == 'services_index' ? 'active' : nil }")

    - if signed_in?
      li.pull-right = "Hi #{current_user.name}. Role: #{current_user.role}"
      li = link_to 'Logg out', "/users/sign_out"
      /- if admin?
        li = link_to('Bytt til Admin modus', toggle_admin_path,
              method: :post) if !admin_menu?
        li = link_to('Bytt til Normal modus', toggle_admin_path,
                    method: :post) if admin_menu?

      - if admin?
        li(class="#{ body_id == 'services_index' ? 'active' : nil }")
          = link_to 'Til reparasjon', services_path()
        li(class="#{ body_id == 'parts_index' ? 'active' : nil }")
          = link_to 'Deler', parts_path
        li(class="#{ body_id == 'users_index' ? 'active' : nil }")
          = link_to 'Kunder', users_path
        li(class="#{ body_id == 'products_index' ? 'active' : nil }")
          = link_to 'Produkter til forsiden', products_path
        /li(class="#{ body_id == 'orders_index' ? 'active' : nil }")
          = link_to 'Bestillinger av servicepakken', orders_path
      li(class="#{ body_id == 'users_show' ? 'active' : nil }")
        = link_to 'Din side', user_path(current_user) unless admin?

  - if !signed_in?
    .container-fluid
      .pull-right
        ul.nav.navbar-nav
         li = link_to 'Logg inn', '/order'
  - if signed_in?
    .container-fluid
      /! Brand and toggle get grouped for better mobile display
      .navbar-header
        button.navbar-toggle.collapsed(aria-expanded="false"
          data-target="#bs-example-navbar-collapse-1"
          data-toggle="collapse"
          type="button")
            span.sr-only Toggle navigation
            span.icon-bar
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          - if admin_menu?
            li(class="#{ body_id == 'services_index' ? 'active' : nil }")
              = link_to 'Til reparasjon', services_path()
            li(class="#{ body_id == 'parts_index' ? 'active' : nil }")
              = link_to 'Deler', parts_path
            li(class="#{ body_id == 'users_index' ? 'active' : nil }")
              = link_to 'Kunder', users_path
            li(class="#{ body_id == 'products_index' ? 'active' : nil }")
              = link_to 'Produkter til forsiden', products_path
            li(class="#{ body_id == 'orders_index' ? 'active' : nil }")
              = link_to 'Bestillinger av servicepakken', orders_path
          li(class="#{ body_id == 'users_show' ? 'active' : nil }")
            = link_to 'Din side', user_path(current_user) unless admin?
        .pull-right
            ul.nav.navbar-nav
              li = link_to('Logout', destroy_user_session_path,  :method=>'delete')

              li = link_to('Bytt til Admin modus', toggle_admin_path,
                    method: :post) if !admin_menu?
              li = link_to('Bytt til Normal modus', toggle_admin_path,
                      method: :post) if admin_menu?
            /= "#{current_user.first_name} = #{current_user.role}"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  = render "layouts/head"
  body(id=body_id )
    = render "layouts/navbar"
    - if content_for?(:breadcrumb)
      ol.breadcrumb = yield(:breadcrumb)
    #content.container
      .flash-messages
        = flash_messages
      = yield

    = render "layouts/footer"

app/views/layouts/bootstrap.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Marcos"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Marcos
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        p &copy; Company 2017

app/views/layouts/frontpage.html.slim
doctype html
html[lang="en"]
  = render "layouts/head"
  body(id=body_id )
    = render "layouts/navbar"
    /nav.navbar.navbar-inverse.navbar-fixed-top[role="navigation"]
      .container
        .navbar-header
          button.navbar-toggle[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"]
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand[href="/"]
            | Marcos Sykkelverksted
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              a[href="#"]
                | About
            li
              a[href="#"]
                | Services
            li
              a[href="#"]
                | Contact
    header.business-header
      .container
        .row
          .col-lg-12
            h1.tagline
              | Marcos Sykkelverksted
            - if content_for?(:businessheader)
              = yield(:businessheader)
    .container
      = flash_messages
      = yield

  = render "layouts/footer"